[workspace]
resolver = "2"
members = ["crates/vtj", "crates/vtj-validate", "crates/parser-mp3", "crates/parser-aac", "crates/parser-opus", "crates/parser-srt", "crates/parser-h264", "crates/parser-flac", "crates/parser-ac3", "crates/parser-pcm", "crates/parser-vorbis", "crates/parser-dts", "crates/parser-webvtt", "crates/parser-ass", "crates/parser-pgs", "crates/parser-mp2", "crates/vmkv-parse", "crates/vtj-stress"]

[workspace.package]
edition = "2021"
version = "0.1.0"
