[package]
name = "vmkv-parser-vobsub"
description = "VMKV parser for VobSub subtitles (.idx + .sub)"
version = "0.1.0"
edition.workspace = true

[lib]
name = "vmkv_parser_vobsub"
path = "src/lib.rs"

[[bin]]
name = "vmkv-parser-vobsub"
path = "src/main.rs"

[dependencies]
vtj = { path = "../vtj" }

[dev-dependencies]
vtj-stress = { path = "../vtj-stress" }
